### ISSUE TITLE
Existing Phoenix websocket

### ISSUE THREAD

**Issue by OvermindDL1** [fbonetti/elm-phoenix-socket#12]
We have a fairly large Phoenix site that uses websockets in a number of ways.  Currently the site is fairly simple, mostly server-rendered, bootstrap + jquery, tried to keep it simple so far.  There are various areas on the sites that setup Phoenix channels over a global websocket connection that is spooled up on demand.  I'm looking into using Elm in a particularly dynamic area of the site (a main page area in addition to a mini version of that main page being embeddable as components in other locations).  How would I make such an element that could take an existing javascript phoenix websocket and make a new Channel on it without creating another websocket link (thus only one websocket connection exists with multiple channels on it, some javascript channels and some Elm channels) as I am not currently seeing a way that can be done.  The backend websocket channel that the Elm section would use would be using Presence fairly heavily, so looking into that being usable as well and the heartbeat and re-connection needs to work like the javascript version as well.

**Comment by fbonetti** [comment]
This type of a question would be more appropriate for a forum like [/r/elm](https://www.reddit.com/r/elm), [/r/javascript](https://www.reddit.com/r/javascript), or maybe even stack overflow. I'd like to limit the issues on this repo to bugs, features, and discussions about the library itself.

I don't know if what you're doing is possible, since the Elm websocket library and the Phoenix javascript library will each create their own `WebSocket` instance.

**Comment by OvermindDL1** [comment]
This would be more of a feature request then.  I need both elm and javascript phoenix libraries to use the same websocket, could be done with either taking the javascript phoenix library and putting it into this elm library, or taking it out of this elm library and using it in javascript.  I would need an integration point in either direction in this library?  :-)
